name: Test

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          /*
          !nz_vineyard_polygons_topo_150k/.table-dataset/feature
        sparse-checkout-cone: true
        fetch-depth: 1

    - name: Kart - Version
      uses: docker://ghcr.io/linz/action-kart:v0.1.0
      with:
        run: |
          kart --version

    # - name: Kart - Clone
    #   run: |
    #     git clone --bare . bare/
    #     cd bare/
    #     kart export nz_vineyard_polygons_topo_150k ../out.gpkg

    # - name: Check Geopackage
    #   run: |
    #     ls -alh out.gpkg
    
    # - name: Setup Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '24'

    # - name: Check geopackage
    #   run: 
    #     node index.ts