name: Test

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest 

    steps:

    - name: Kart - Setup
      run: |
        cd ${{ runner.temp }}/ # ensure we don't write anything into the working dir
        wget https://github.com/koordinates/kart/releases/download/v0.16.1/Kart-0.16.1-linux-x86_64.tar.gz
        tar xvf Kart-0.16.1-linux-x86_64.tar.gz
        echo "$PWD/Kart-0.16.1-linux-x86_64/kart/" >> $GITHUB_PATH

    - name: Kart - Version
      run: |
        kart --version

    - name: Kart - Clone
      run: |
        echo $PWD
        ls -alh
        kart clone ${GITHUB_REPOSITORY}
        kart checkout ${GITHUB_SHA}

    - name: Kart - Status
      run: |
        kart status
