name: Test

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest 

    container:
      image: ghcr.io/linz/action-kart:v0.1.1

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # sparse-checkout: |
        #   /*
        #   !nz_topo_map_sheet/.table-dataset/feature
        #   !nz_vineyard_polygons_topo_150k/.table-dataset/feature
        # sparse-checkout-cone-mode: false
        fetch-depth: 1

    - name: Kart - Version
      run: |
        kart --version

        ls -alh

    - name: Kart - Clone
      run: |
        git clone --bare .git .git-bare
        
        kart -C .git-bare export nz_topo_map_sheet nz_topo_map_sheet.gpkg
        kart -C .git-bare export nz_vineyard_polygons_topo_150k nz_vineyard_polygons_topo_150k.gpkg

    - name: Check Geopackages
      run: |
        ls -alh *.gpkg
    
    # - name: Setup Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '24'

    # - name: Check geopackage
    #   run: 
    #     node index.ts