name: Test

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest 

    steps:

    - name: Set up Kart
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/koordinates/kart/releases/download/v0.16.1/Kart-0.16.1-linux-x86_64.tar.gz 
        tar xvf Kart-0.16.1-linux-x86_64.tar.gz
        echo "$PWD/Kart-0.16.1-linux-x86_64/kart/" >> $GITHUB_PATH

    - name: Check kart
      run: |
        kart --version
