name: Test

on: [push]

jobs:
  clone:
    runs-on: ubuntu-latest 

    container:
      image: ghcr.io/linz/action-kart:v0.1.2

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # sparse-checkout: |
        #   /*
        #   !nz_topo_map_sheet/.table-dataset/feature
        #   !nz_vineyard_polygons_topo_150k/.table-dataset/feature
        # sparse-checkout-cone-mode: false
        fetch-depth: 1

    - name: Kart - Version
      run: |
        kart --version

        ls -alh

    - name: Kart - Clone
      run: |
        # Convert the repo to bare so kart can export from it
        git clone --bare .git .git-bare

        kart -C .git-bare export nz_topo_map_sheet nz_topo_map_sheet.gpkg
        kart -C .git-bare export nz_vineyard_polygons_topo_150k nz_vineyard_polygons_topo_150k.gpkg

    - name: Check Geopackages
      run: |
        ls -alh *.gpkg

    - name: Convert to parquet
      run: |
        gdal vector convert nz_topo_map_sheet.gpkg nz_topo_map_sheet.parquet --lco compression=zstd --lco compression_level=15
        gdal vector convert nz_vineyard_polygons_topo_150k.gpkg nz_vineyard_polygons_topo_150k.parquet --lco compression=zstd --lco compression_level=15
    
    - name: Check parquet
      run: |
        ls -alh *.parquet

    - name: Run tests
      run: |
        uv run scripts/validate-map-sheet.py
